### ISSUE TITLE
Error: API returned an error: {"status":"error","error":"Internal Server Error"}

### ISSUE THREAD

**Issue by SixFiveSoftware** [jamesreggio/unravel#2]
Just installed the Chrome extension a few minutes ago. Went to Fabric and opened a crash I just recently had. Clicking the blue C icon for Unravel shows the following error and suggests logging an issue:

Error: API returned an error: {"status":"error","error":"Internal Server Error"}
    at receiveMessage (file:///Users/BJ/Library/Application%20Support/Google/Chrome/Default/Extensions/opccdmdchkjidmnneegkgglhgigpkopa/0.0.3_0/lib/inject.js:2:571)
    at file:///Users/BJ/Library/Application%20Support/Google/Chrome/Default/Extensions/opccdmdchkjidmnneegkgglhgigpkopa/0.0.3_0/lib/inject.js:2:130

**Comment by jamesreggio** [comment]
Thanks for trying out the extension!

It looks like the Crashlytics API changed over the weekend, but I've resolved the issue just now in 25b51812ed71d9fd9dc23508bb0fa3bfda39c35c and the update is now available as version 0.0.4 in the Chrome Web Store.

I would appreciate it if you [manually forced your Chrome extensions to update](http://lifehacker.com/5805239/how-to-manually-update-your-chrome-extensions) and then let me know if you still experience this problem.

**Comment by SixFiveSoftware** [comment]
It works! Thanks James :+1:
